### ISSUE TITLE
Ability to do 'week' newsletters instead of only 'day'

### ISSUE THREAD

**Issue by nikitavoloboev** [caarlos0/watchub#194]
Would really love this feature as the day to day changes are less interesting to me.

Thank you for an amazing tool. ❤️

**Comment by Lissy93** [comment]
+1 weekly mails would be awesome!
I was looking through the code, hoping to implement this, but ended up getting quite lost. 
This tool is a lot of fun, and thank you @caarlos0 for building, maintaining and hosting it 💖
