### ISSUE TITLE
dont count forks as repos

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/watchub#44]
should not count 'em

**Comment by caarlos0** [comment]
done

**Comment by intika** [comment]
This is may be a mistake, while it's true for most forked repos, it's not true for a "true fork" that would replace/provide-alternative of the mainstream repo. 

May be this should be implemented as a setting instead of being forced on

**Comment by intika** [comment]
may be reopen https://github.com/caarlos0/watchub/issues/23
