### ISSUE TITLE
Feature request: selective enablement of organizations and repositories

### ISSUE THREAD

**Issue by mathuin** [caarlos0/watchub#45]
It would be nice to be able to selectively enable organizations for watchub to follow.

It would be even nicer to be able to selectively enable repositories within those organizations and those owned directly by the user.

Reasoning: there are some repos in some orgs that I'm in where I don't care who follows them, but there are a few repos about which I really *do* care.  Less noise means higher quality signal means more value from the tool.

**Comment by caarlos0** [comment]
Seems like a valid feature for me.

Will try to work into it next few days..

**Comment by mathuin** [comment]
I am no longer part of the orgs which inspired this feature request, so I'm unsubscribing from this issue.  I do think that this is a desirable feature for others, though, so I'm not closing it.  Thank you!

**Comment by intika** [comment]
Should be closed, already available through github's "organization access" when the app is linked or on the setting page... the only limitation we can not deny access once allowed (still doable if we revoke the app auth and re add it)

**Comment by caarlos0** [comment]
> Should be closed, already available through github's "organization access" when the app is linked or on the setting page... the only limitation we can not deny access once allowed (still doable if we revoke the app auth and re add it)

make sense to me 🤔
