### ISSUE TITLE
Site watchub.pw offline ? 

### ISSUE THREAD

**Issue by intika** [caarlos0/watchub#53]
Are you planning to bring back the site ? 
Thank you for you work :)

**Comment by caarlos0** [comment]
It is up right?

**Comment by intika** [comment]
nope it's down... i am trying right now to setup it locally, nice work by the way :) i am struggling with the database... `level=error message="failed to get executions" error="pq: relation \"tokens\" does not exist"` it does not seem to create the database automatically.... 

any way i am going to try the website over vpn may be it's my connection but i don't think i'll post back in 5 min

**Comment by intika** [comment]
weird... look like it's a dns issue... i am trying to figure that out... i'll post back what it was exactly

**Comment by caarlos0** [comment]
yeah, its up here and monitoring didn't fire... 

it doesn't create the DB locally, I think it is on CONTRIBUTING.md...

**Comment by intika** [comment]
Thanks for taking time to answer it's appreciated :) basically my DNS server is using `DNS over TLS` + `DNSSEC` fetching from upstream over a special route... any way the problem was caused with the combination of (Cloudflare DNS + DNSSEC) nothing wrong on my config because it works with other providers... it's just a cloudflare bug, i just updated my config to avoid such issue... 

I guess it's caused by the used ssl certificate on your domain and Cloudflare bug... any way i reported [back that to cloudflare](https://community.cloudflare.com/t/1-1-1-1-dnssec-servfail-on-some-domains/) (need to be logged in to see it)

For curious one; to reproduce this bug we can use `unbound` + `1.1.1.1` + [DNSSEC](https://nlnetlabs.nl/documentation/unbound/howto-anchor/)... to setup unbound it's very easy an example can be found [here](https://www.prado.it/2012/04/14/how-to-configure-unbound-on-ubuntu-11-10/)

An other thing about your project is that i searched a long time google/github before reaching watchub i guess it's why you don't have a lot of stars/attention to it... you should add some topic to the project like stars/unstar/follow/unfollow and also may be post something about it on reddit or else. 

> CONTRIBUTING.md...

looool it was there all the time lol i though that file was for licensing or something... i figured-out/searched all the different setup commands (but the DB) that's funny because i was thinking of using the sql file to fix the db like you advice on CONTRIBUTING... any way i still did not use the service i will check that out and contribute if i may add this or that feature. 

Thanks you for your work and for the rest ;)

**Comment by intika** [comment]
Also SSL should be enabled by default for your site, it's kind a must since it exchange sensitive information with github (not a lot exposed but...) can be done freely with let's encrypt or cloudflare or other similar solution.

**Comment by intika** [comment]
**Update: cloudflare answer:**

watchub.pw. has a CNAME record pointing to watchub.herokuapp.com..

It’s illegal for the apex of a zone to have a CNAME record. Sometimes resolvers will return SERVFAIL.

You’re probably running into this issue:
[GitLab - CNAME breaks DS queries if CNAME is at apex (non-compliant auth side) (#359)](https://gitlab.labs.nic.cz/knot/knot-resolver/issues/359)

kresd replies incorrectly for `name.example. DS` queries if `name.example.` has CNAME at apex `name.example.`. This seems to affect only non-compliant servers which allow CNAME at apex. **Such zones are illegal...

When Unbound sends a watchub.pw. DS query, 1.1.1.1 may return the CNAME instead of a NODATA response, leaving Unbound unable to figure out whether the zone uses DNSSEC, and forcing it to respond with SERVFAIL.

watchub.pw. won’t work reliably as long as it doesn’t follow the DNS standards.

**Comment by caarlos0** [comment]
thanks for the investigation, will take a look on this soon.

**Comment by intika** [comment]
- Just update the domain DNS record should fix this... 
- Or subscribe for a free account @cloudflare or similar provider, while it will fix the problem it will also make SSL available with zero effort (other than updating the code links to https)

Also an other thing, sorry to bother you about it (i am using my opened issues list to manage the work i need to do can you please reopen an other issue or add a todo for the dns-update/fix)

**Comment by caarlos0** [comment]
yeah, I'm adding it to my cloudflare account :)

**Comment by caarlos0** [comment]
should be good now :) 

thanks for the issue!

**Comment by intika** [comment]
just to let you know i am running https://starhub.be (based on your project) with many additional features... it could interest you ;)

**Comment by caarlos0** [comment]
cool :D

**Comment by intika** [comment]
Thank you carlos :) feel free to merge back this or that or the whole thing ;) from what i added... and let me know if there is any think ;) 
By the way there is a little issue on your version, metrics should not be public but it's up to you :)

**Comment by intika** [comment]
Thank you carlos :)... also let me know if there is any think (if my fork disturb or something) ;) 
By the way there is a little issue on your version, metrics should not be public but it's up to you :)
